//>>built
define("dojo/nls/dojo_ca",{"dojo/cldr/nls/gregorian":{"days-standAlone-short":"dg. dl. dm. dc. dj. dv. ds.".split(" "),"months-format-narrow":"GFMAMJJASOND".split(""),"quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"dia de la setmana","dateFormatItem-yQQQ":"QQQ y","dateFormatItem-yMEd":"E, d.M.y","dateFormatItem-GyMMMEd":"G y MMM d, E","dateFormatItem-MMMEd":"E d MMM",eraNarrow:["aC","dC"],"days-format-short":"dg. dl. dt. dc. dj. dv. ds.".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"d MMMM 'de' y","months-format-wide":"de gener;de febrer;de mar\u00e7;d\u2019abril;de maig;de juny;de juliol;d\u2019agost;de setembre;d\u2019octubre;de novembre;de desembre".split(";"),"dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"p.m.","dateFormat-full":"EEEE d MMMM 'de' y","dateFormatItem-Md":"d/M","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateFormatItem-yMd":"d/M/y","field-era":"era","dateFormatItem-yM":"M/y","months-standAlone-wide":"gener febrer mar\u00e7 abril maig juny juliol agost setembre octubre novembre desembre".split(" "),
"timeFormat-short":"H.mm","quarters-format-wide":["1r trimestre","2n trimestre","3r trimestre","4t trimestre"],"dateFormatItem-yQQQQ":"QQQQ y","timeFormat-long":"H.mm.ss z","field-year":"any","dateFormatItem-yMMM":"LLL y","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"hora","months-format-abbr":"de gen.;de febr.;de mar\u00e7;d\u2019abr.;de maig;de juny;de jul.;d\u2019ag.;de set.;d\u2019oct.;de nov.;de des.".split(";"),"timeFormat-full":"H.mm.ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})",
"field-day-relative+0":"avui","field-day-relative+1":"dem\u00e0","dateFormatItem-GyMMMd":"G y MMM d","dateFormatItem-H":"H","months-standAlone-abbr":"gen. febr. mar\u00e7 abr. maig juny jul. ag. set. oct. nov. des.".split(" "),"quarters-format-abbr":["1T","2T","3T","4T"],"quarters-standAlone-wide":["1r trimestre","2n trimestre","3r trimestre","4t trimestre"],"dateFormatItem-Gy":"G y","dateFormatItem-M":"L","days-standAlone-wide":"Diumenge Dilluns Dimarts Dimecres Dijous Divendres Dissabte".split(" "),
"timeFormat-medium":"H.mm.ss","dateFormatItem-Hm":"H.mm","quarters-standAlone-abbr":["1T","2T","3T","4T"],eraAbbr:["aC","dC"],"field-minute":"minut","field-dayperiod":"a.m./p.m.","days-standAlone-abbr":"dg dl dt dc dj dv ds".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm.ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"ahir","dateFormatItem-h":"h a","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a.m.","dateFormatItem-MMMd":"d MMM","dateFormatItem-MEd":"E d/M",
"dateTimeFormat-full":"{1} {0}","field-day":"dia","days-format-wide":"diumenge dilluns dimarts dimecres dijous divendres dissabte".split(" "),"field-zone":"zona","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y","months-standAlone-narrow":"gfmamjjasond".split(""),"dateFormatItem-hm":"h.mm a","dateTimeFormats-appendItem-Year":"{1} {0}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"dg. dl. dt. dc. dj. dv. ds.".split(" "),
eraNames:["abans de Crist","despr\u00e9s de Crist"],"dateFormatItem-yMMMd":"d MMM y","days-format-narrow":"dg dl dt dc dj dv ds".split(" "),"days-standAlone-narrow":"dg dl dt dc dj dv ds".split(" "),"dateFormatItem-MMM":"LLL","field-month":"mes","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"a.m.","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormat-short":"dd/MM/yy","field-second":"segon","dateFormatItem-yMMMEd":"E, d MMM, y",
"dateFormatItem-Ed":"E d","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"setmana","dateFormat-medium":"dd/MM/y","dayPeriods-format-narrow-pm":"p.m.","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"H.mm.ss","dateFormatItem-hms":"h.mm.ss a","dateFormatItem-GyMMM":"G y MMM","dateFormatItem-yMM":"MM/y","field-day-relative+2":"dem\u00e0 passat","dateFormatItem-MMMMd":"d MMMM","field-day-relative+-2":"abans d'ahir","dateFormatItem-yMMMM":"LLLL 'de' y","field-year-relative+-1":"\u00daltim any",
"field-month-relative+-1":"\u00daltim mes","dateFormatItem-MMMMEd":"E d MMMM","field-month-relative+0":"Aquest mes","field-month-relative+1":"Mes seg\u00fcent","field-year-relative+0":"Aquest any","field-week-relative+-1":"\u00daltima setmana","field-year-relative+1":"Any seg\u00fcent","dateFormatItem-mmss":"mm:ss","field-week-relative+0":"Aquesta setmana","field-week-relative+1":"Setmana seg\u00fcent",_localized:{}},"dijit/nls/loading":{loadingState:"S'est\u00e0 carregant...",errorState:"Ens sap greu. S'ha produ\u00eft un error.",
_localized:{}},"dojox/grid/enhanced/nls/EnhancedGrid":{singleSort:"Ordre \u00fanic",nestedSort:"Ordre imbricat",ascending:"Feu clic per ordenar de forma ascendent",descending:"Feu clic per ordenar de forma descendent",sortingState:"${0} - ${1}",unsorted:"No ordenis aquesta finestra",indirectSelectionRadio:"Fila ${0}, selecci\u00f3 individual, quadre d'opci\u00f3",indirectSelectionCheckBox:"Fila ${0}, selecci\u00f3 m\u00faltiple, quadre de selecci\u00f3",selectAll:"Selecciona-ho tot",_localized:{}},
"dijit/form/nls/validate":{invalidMessage:"El valor introdu\u00eft no \u00e9s v\u00e0lid",missingMessage:"Aquest valor \u00e9s necessari",rangeMessage:"Aquest valor \u00e9s fora de l'interval",_localized:{}},"dijit/form/nls/ComboBox":{previousMessage:"Opcions anteriors",nextMessage:"M\u00e9s opcions",_localized:{}},"dojo/cldr/nls/number":{scientificFormat:"#E0","currencySpacing-afterCurrency-currencyMatch":"[:^S:]",infinity:"\u221e",list:";",percentSign:"%",minusSign:"-","currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]",
"decimalFormat-short":"000\u00a0B","currencySpacing-afterCurrency-insertBetween":"\u00a0",nan:"NaN",plusSign:"+","currencySpacing-afterCurrency-surroundingMatch":"[:digit:]","currencySpacing-beforeCurrency-currencyMatch":"[:^S:]",currencyFormat:"\u00a4#,##0.00;(\u00a4#,##0.00)",perMille:"\u2030",group:".",percentFormat:"#,##0%","decimalFormat-long":"000 bilions",decimalFormat:"#,##0.###",decimal:",","currencySpacing-beforeCurrency-insertBetween":"\u00a0",exponential:"E",_localized:{}},"dojo/cldr/nls/currency":{USD_symbol:"US$",
CAD_symbol:"CA$",GBP_symbol:"\u00a3",HKD_symbol:"HK$",JPY_symbol:"JP\u00a5",AUD_symbol:"AU$",CNY_symbol:"\u00a5",EUR_symbol:"\u20ac",HKD_displayName:"d\u00f2lar de Hong Kong",CHF_displayName:"franc su\u00eds",CAD_displayName:"d\u00f2lar canadenc",CNY_displayName:"iuan renmimbi xin\u00e8s",AUD_displayName:"d\u00f2lar australi\u00e0",JPY_displayName:"ien japon\u00e8s",USD_displayName:"d\u00f2lar dels Estats Units",GBP_displayName:"lliura esterlina brit\u00e0nica",EUR_displayName:"euro",_localized:{}},
"dijit/_editor/nls/commands":{bold:"Negreta",copy:"Copia",cut:"Retalla","delete":"Suprimeix",indent:"Sagnat",insertHorizontalRule:"Regla horitzontal",insertOrderedList:"Llista numerada",insertUnorderedList:"Llista de vinyetes",italic:"Cursiva",justifyCenter:"Alineaci\u00f3 centrada",justifyFull:"Justifica",justifyLeft:"Alineaci\u00f3 a l'esquerra",justifyRight:"Alineaci\u00f3 a la dreta",outdent:"Sagnat a l'esquerra",paste:"Enganxa",redo:"Ref\u00e9s",removeFormat:"Elimina el format",selectAll:"Selecciona-ho tot",
strikethrough:"Ratllat",subscript:"Sub\u00edndex",superscript:"Super\u00edndex",underline:"Subratllat",undo:"Desf\u00e9s",unlink:"Elimina l'enlla\u00e7",createLink:"Crea un enlla\u00e7",toggleDir:"Inverteix la direcci\u00f3",insertImage:"Insereix imatge",insertTable:"Insereix/edita la taula",toggleTableBorder:"Inverteix els contorns de taula",deleteTable:"Suprimeix la taula",tableProp:"Propietat de taula",htmlToggle:"Font HTML",foreColor:"Color de primer pla",hiliteColor:"Color de fons",plainFormatBlock:"Estil de par\u00e0graf",
formatBlock:"Estil de par\u00e0graf",fontSize:"Mida del tipus de lletra",fontName:"Nom del tipus de lletra",tabIndent:"Sagnat",fullScreen:"Commuta pantalla completa",viewSource:"Visualitza font HTML",print:"Imprimeix",newPage:"P\u00e0gina nova",systemShortcut:"L'acci\u00f3 \"${0}\" \u00e9s l'\u00fanica disponible al navegador utilitzant una drecera del teclat. Utilitzeu ${1}.",ctrlKey:"control+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/nls/common":{buttonOk:"D'acord",buttonCancel:"Cancel\u00b7la",
buttonSave:"Desa",itemClose:"Tanca",_localized:{}}});
//# sourceMappingURL=dojo_ca.js.map