//>>built
define("dojo/nls/dojo_es-es",{"dojo/cldr/nls/gregorian":{"days-standAlone-short":"DLMXJVS".split(""),"months-format-narrow":"EFMAMJJASOND".split(""),"quarters-standAlone-narrow":["1T","2T","3T","4T"],"field-weekday":"d\u00eda de la semana","dateFormatItem-yQQQ":"QQQ y","dateFormatItem-yMEd":"EEE, d/M/y","dateFormatItem-GyMMMEd":"E, d 'de' MMMM 'de' y G","dateFormatItem-MMMEd":"E d MMM",eraNarrow:["a.C.","d.C."],"days-format-short":"DLMXJVS".split(""),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"d 'de' MMMM 'de' y","months-format-wide":"enero febrero marzo abril mayo junio julio agosto septiembre octubre noviembre diciembre".split(" "),"dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"p.m.","dateFormat-full":"EEEE, d 'de' MMMM 'de' y","dateFormatItem-Md":"d/M","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateFormatItem-yMd":"d/M/y","field-era":"era","dateFormatItem-yM":"M/y","months-standAlone-wide":"enero febrero marzo abril mayo junio julio agosto septiembre octubre noviembre diciembre".split(" "),
"timeFormat-short":"HH:mm","quarters-format-wide":["1er trimestre","2\u00ba trimestre","3er trimestre","4\u00ba trimestre"],"dateFormatItem-yQQQQ":"QQQQ 'de' y","timeFormat-long":"HH:mm:ss z","field-year":"a\u00f1o","dateFormatItem-yMMM":"MMM y","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"hora","months-format-abbr":"ene feb mar abr may jun jul ago sep oct nov dic".split(" "),"timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"hoy",
"field-day-relative+1":"ma\u00f1ana","dateFormatItem-GyMMMd":"d MMM y G","dateFormatItem-H":"HH","months-standAlone-abbr":"ene feb mar abr mayo jun jul ago sep oct nov dic".split(" "),"quarters-format-abbr":["T1","T2","T3","T4"],"quarters-standAlone-wide":["1.er trimestre","2.\u00ba trimestre","3.er trimestre","4.\u00ba trimestre"],"dateFormatItem-Gy":"y G","dateFormatItem-M":"L","days-standAlone-wide":"domingo lunes martes mi\u00e9rcoles jueves viernes s\u00e1bado".split(" "),"timeFormat-medium":"HH:mm:ss",
"dateFormatItem-Hm":"HH:mm","quarters-standAlone-abbr":["T1","T2","T3","T4"],eraAbbr:["a.C.","d.C."],"field-minute":"minuto","field-dayperiod":"periodo del d\u00eda","days-standAlone-abbr":"dom lun mar mi\u00e9 jue vie s\u00e1b".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1T","2T","3T","4T"],"field-day-relative+-1":"ayer","dateFormatItem-h":"hh a","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"AM","dateFormatItem-MMMd":"d MMM","dateFormatItem-MEd":"E, d/M",
"dateTimeFormat-full":"{1} {0}","field-day":"d\u00eda","days-format-wide":"domingo lunes martes mi\u00e9rcoles jueves viernes s\u00e1bado".split(" "),"field-zone":"zona","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y","months-standAlone-narrow":"EFMAMJJASOND".split(""),"dateFormatItem-hm":"hh:mm a","dateTimeFormats-appendItem-Year":"{1} {0}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"dom lun mar mi\u00e9 jue vie s\u00e1b".split(" "),
eraNames:["antes de Cristo","anno D\u00f3mini"],"dateFormatItem-yMMMd":"d MMM y","days-format-narrow":"DLMXJVS".split(""),"days-standAlone-narrow":"DLMXJVS".split(""),"dateFormatItem-MMM":"LLL","field-month":"mes","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"a.m.","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormat-short":"dd/MM/yy","field-second":"segundo","dateFormatItem-yMMMEd":"EEE, d 'de' MMMM 'de' y",
"dateFormatItem-Ed":"E d","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"semana","dateFormat-medium":"dd/MM/y","dayPeriods-format-narrow-pm":"PM","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"hh:mm:ss a","dateFormatItem-GyMMM":"MMM y G","dateFormatItem-yMM":"MM/y","dateFormatItem-MMMdd":"dd-MMM","dateFormatItem-MMdd":"dd/MM","field-day-relative+2":"pasado ma\u00f1ana","dateFormatItem-MMMMd":"d 'de' MMMM","field-day-relative+-2":"antes de ayer",
"dateFormatItem-yMMMM":"MMMM 'de' y","field-year-relative+-1":"el a\u00f1o pasado","field-month-relative+-1":"el mes pasado","dateFormatItem-MMd":"d/MM","field-month-relative+0":"este mes","field-month-relative+1":"el pr\u00f3ximo mes","field-year-relative+0":"este a\u00f1o","field-week-relative+-1":"la semana pasada","field-year-relative+1":"el pr\u00f3ximo a\u00f1o","field-week-relative+0":"esta semana","field-week-relative+1":"la pr\u00f3xima semana",_localized:{}},"dijit/nls/loading":{loadingState:"Cargando...",
errorState:"Lo siento, se ha producido un error",_localized:{}},"dojox/grid/enhanced/nls/EnhancedGrid":{singleSort:"Orden \u00fanico",nestedSort:"Orden anidado",ascending:"Pulse para ordenar de forma ascendente",descending:"Pulse para ordenar de forma descendente",sortingState:"${0} - ${1}",unsorted:"No ordenar esta columna",indirectSelectionRadio:"Fila ${0}, selecci\u00f3n \u00fanica, bot\u00f3n de selecci\u00f3n",indirectSelectionCheckBox:"Fila ${0}, selecci\u00f3n m\u00faltiple, recuadro de selecci\u00f3n",
selectAll:"Seleccionar todo",_localized:{}},"dijit/form/nls/validate":{invalidMessage:"El valor especificado no es v\u00e1lido.",missingMessage:"Este valor es necesario.",rangeMessage:"Este valor est\u00e1 fuera del intervalo.",_localized:{}},"dijit/form/nls/ComboBox":{previousMessage:"Opciones anteriores",nextMessage:"M\u00e1s opciones",_localized:{}},"dojo/cldr/nls/number":{scientificFormat:"#E0","currencySpacing-afterCurrency-currencyMatch":"[:^S:]",infinity:"\u221e",list:";",percentSign:"%",minusSign:"-",
"currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]","decimalFormat-short":"000\u00a0B","currencySpacing-afterCurrency-insertBetween":"\u00a0",nan:"NaN",plusSign:"+","currencySpacing-afterCurrency-surroundingMatch":"[:digit:]","currencySpacing-beforeCurrency-currencyMatch":"[:^S:]",currencyFormat:"#,##0.00\u00a0\u00a4",perMille:"\u2030",group:".",percentFormat:"#,##0%","decimalFormat-long":"000 billones",decimalFormat:"#,##0.###",decimal:",","currencySpacing-beforeCurrency-insertBetween":"\u00a0",
exponential:"E",_localized:{}},"dojo/cldr/nls/currency":{USD_symbol:"US$",CAD_symbol:"CA$",GBP_symbol:"\u00a3",HKD_symbol:"HK$",JPY_symbol:"JP\u00a5",AUD_symbol:"AU$",CNY_symbol:"CN\u00a5",EUR_symbol:"\u20ac",HKD_displayName:"d\u00f3lar de Hong Kong",CHF_displayName:"franco suizo",CAD_displayName:"d\u00f3lar canadiense",CNY_displayName:"yuan chino",AUD_displayName:"d\u00f3lar australiano",JPY_displayName:"yen japon\u00e9s",USD_displayName:"d\u00f3lar estadounidense",GBP_displayName:"libra esterlina brit\u00e1nica",
EUR_displayName:"euro",_localized:{}},"dijit/_editor/nls/commands":{bold:"Negrita",copy:"Copiar",cut:"Cortar","delete":"Suprimir",indent:"Sangr\u00eda",insertHorizontalRule:"Regla horizontal",insertOrderedList:"Lista numerada",insertUnorderedList:"Lista con vi\u00f1etas",italic:"Cursiva",justifyCenter:"Alinear centro",justifyFull:"Justificar",justifyLeft:"Alinear izquierda",justifyRight:"Alinear derecha",outdent:"Anular sangr\u00eda",paste:"Pegar",redo:"Rehacer",removeFormat:"Eliminar formato",selectAll:"Seleccionar todo",
strikethrough:"Tachado",subscript:"Sub\u00edndice",superscript:"Super\u00edndice",underline:"Subrayado",undo:"Deshacer",unlink:"Eliminar enlace",createLink:"Crear enlace",toggleDir:"Conmutar direcci\u00f3n",insertImage:"Insertar imagen",insertTable:"Insertar/Editar tabla",toggleTableBorder:"Conmutar borde de tabla",deleteTable:"Suprimir tabla",tableProp:"Propiedad de tabla",htmlToggle:"Fuente HTML",foreColor:"Color de primer plano",hiliteColor:"Color de segundo plano",plainFormatBlock:"Estilo de p\u00e1rrafo",
formatBlock:"Estilo de p\u00e1rrafo",fontSize:"Tama\u00f1o de font",fontName:"Nombre de font",tabIndent:"Sangr\u00eda de tabulador",fullScreen:"Conmutar pantalla completa",viewSource:"Ver fuente HTML",print:"Imprimir",newPage:"Nueva p\u00e1gina",systemShortcut:'La acci\u00f3n "${0}" s\u00f3lo est\u00e1 disponible en su navegador mediante un atajo de teclado. Utilice ${1}.',ctrlKey:"control+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/nls/common":{buttonOk:"Aceptar",buttonCancel:"Cancelar",buttonSave:"Guardar",
itemClose:"Cerrar",_localized:{}}});
//# sourceMappingURL=dojo_es-es.js.map