//>>built
define("dojo/nls/dojo_pt-br",{"dojo/cldr/nls/gregorian":{"days-standAlone-short":"dom seg ter qua qui sex s\u00e1b".split(" "),"months-format-narrow":"JFMAMJJASOND".split(""),"quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Dia da semana","dateFormatItem-yQQQ":"y QQQ","dateFormatItem-yMEd":"E, dd/MM/y","dateFormatItem-GyMMMEd":"E, d 'de' MMM 'de' y G","dateFormatItem-MMMEd":"E, d 'de' MMM",eraNarrow:["a.C.","d.C."],"days-format-short":"dom seg ter qua qui sex s\u00e1b".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"d 'de' MMMM 'de' y","months-format-wide":"janeiro fevereiro mar\u00e7o abril maio junho julho agosto setembro outubro novembro dezembro".split(" "),"dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE, d 'de' MMMM 'de' y","dateFormatItem-Md":"d/M","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateFormatItem-yMd":"dd/MM/y","field-era":"Era","dateFormatItem-yM":"MM/y","months-standAlone-wide":"janeiro fevereiro mar\u00e7o abril maio junho julho agosto setembro outubro novembro dezembro".split(" "),
"timeFormat-short":"HH:mm","quarters-format-wide":["1\u00ba trimestre","2\u00ba trimestre","3\u00ba trimestre","4\u00ba trimestre"],"dateFormatItem-yQQQQ":"y QQQQ","timeFormat-long":"HH:mm:ss z","field-year":"Ano","dateFormatItem-yMMM":"MMM 'de' y","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Hora","months-format-abbr":"jan fev mar abr mai jun jul ago set out nov dez".split(" "),"timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"Hoje",
"field-day-relative+1":"Amanh\u00e3","dateFormatItem-GyMMMd":"d 'de' MMM 'de' y G","dateFormatItem-H":"HH","months-standAlone-abbr":"jan fev mar abr mai jun jul ago set out nov dez".split(" "),"quarters-format-abbr":["T1","T2","T3","T4"],"quarters-standAlone-wide":["1\u00ba trimestre","2\u00ba trimestre","3\u00ba trimestre","4\u00ba trimestre"],"dateFormatItem-Gy":"y G","dateFormatItem-M":"L","days-standAlone-wide":"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),
"timeFormat-medium":"HH:mm:ss","dateFormatItem-Hm":"HH:mm","quarters-standAlone-abbr":["T1","T2","T3","T4"],eraAbbr:["a.C.","d.C."],"field-minute":"Minuto","field-dayperiod":"Per\u00edodo do dia","days-standAlone-abbr":"dom seg ter qua qui sex s\u00e1b".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"Ontem","dateFormatItem-h":"h a","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-MMMd":"d 'de' MMM",
"dateFormatItem-MEd":"E, dd/MM","dateTimeFormat-full":"{1} {0}","field-day":"Dia","days-format-wide":"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),"field-zone":"Fuso","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y","months-standAlone-narrow":"JFMAMJJASOND".split(""),"dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Year":"{1} {0}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM",
"days-format-abbr":"dom seg ter qua qui sex s\u00e1b".split(" "),eraNames:["Antes de Cristo","Ano do Senhor"],"dateFormatItem-yMMMd":"d 'de' MMM 'de' y","days-format-narrow":"DSTQQSS".split(""),"days-standAlone-narrow":"DSTQQSS".split(""),"dateFormatItem-MMM":"LLL","field-month":"M\u00eas","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormat-short":"dd/MM/yy",
"field-second":"Segundo","dateFormatItem-yMMMEd":"E, d 'de' MMM 'de' y","dateFormatItem-Ed":"E, d","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"Semana","dateFormat-medium":"dd/MM/y","dayPeriods-format-narrow-pm":"p","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM 'de' y G","dateFormatItem-yMM":"MM/y","dayPeriods-format-wide-morning":"manh\u00e3","dayPeriods-format-wide-noon":"meio-dia","dateFormatItem-MMdd":"dd/MM",
"field-day-relative+2":"Depois de amanh\u00e3","dateFormatItem-HHmmss":"HH:mm:ss","dayPeriods-format-wide-night":"noite","field-day-relative+-2":"Anteontem","field-year-relative+-1":"Ano passado","field-month-relative+-1":"M\u00eas passado","dateFormatItem-HHmm":"HH:mm","dayPeriods-format-wide-afternoon":"tarde","field-month-relative+0":"Este m\u00eas","field-month-relative+1":"Pr\u00f3ximo m\u00eas","field-year-relative+0":"Este ano","field-week-relative+-1":"Semana passada","field-year-relative+1":"Pr\u00f3ximo ano",
"field-week-relative+0":"Esta semana","field-week-relative+1":"Pr\u00f3xima semana",_localized:{}},"dijit/nls/loading":{loadingState:"Carregando...",errorState:"Desculpe, ocorreu um erro",_localized:{}},"dojox/grid/enhanced/nls/EnhancedGrid":{singleSort:"Classifica\u00e7\u00e3o \u00danica",nestedSort:"Classifica\u00e7\u00e3o Aninhada",ascending:"Clique para classificar de modo Crescente",descending:"Clique para classificar de modo Decrescente",sortingState:"${0} - ${1}",unsorted:"N\u00e3o classificar esta coluna",
indirectSelectionRadio:"Linha ${0}, sele\u00e7\u00e3o \u00fanica, bot\u00e3o de sele\u00e7\u00e3o",indirectSelectionCheckBox:"Linha ${0}, sele\u00e7\u00e3o m\u00faltipla, caixa de sele\u00e7\u00e3o",selectAll:"Selecionar todos",_localized:{}},"dijit/form/nls/validate":{invalidMessage:"O valor inserido n\u00e3o \u00e9 v\u00e1lido.",missingMessage:"Este valor \u00e9 necess\u00e1rio.",rangeMessage:"Este valor est\u00e1 fora do intervalo. ",_localized:{}},"dijit/form/nls/ComboBox":{previousMessage:"Op\u00e7\u00f5es anteriores",
nextMessage:"Mais op\u00e7\u00f5es",_localized:{}},"dojo/cldr/nls/number":{scientificFormat:"#E0","currencySpacing-afterCurrency-currencyMatch":"[:^S:]",infinity:"\u221e",list:";",percentSign:"%",minusSign:"-","currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]","decimalFormat-short":"000\u00a0tri","currencySpacing-afterCurrency-insertBetween":"\u00a0",nan:"NaN",plusSign:"+","currencySpacing-afterCurrency-surroundingMatch":"[:digit:]","currencySpacing-beforeCurrency-currencyMatch":"[:^S:]",
currencyFormat:"\u00a4#,##0.00;(\u00a4#,##0.00)",perMille:"\u2030",group:".",percentFormat:"#,##0%","decimalFormat-long":"000 trilh\u00f5es",decimalFormat:"#,##0.###",decimal:",","currencySpacing-beforeCurrency-insertBetween":"\u00a0",exponential:"E",_localized:{}},"dojo/cldr/nls/currency":{USD_symbol:"US$",CAD_symbol:"CA$",GBP_symbol:"\u00a3",HKD_symbol:"HK$",JPY_symbol:"JP\u00a5",AUD_symbol:"AU$",CNY_symbol:"CN\u00a5",EUR_symbol:"\u20ac",HKD_displayName:"D\u00f3lar de Hong Kong",CHF_displayName:"Franco su\u00ed\u00e7o",
CAD_displayName:"D\u00f3lar canadense",CNY_displayName:"Yuan chin\u00eas",AUD_displayName:"D\u00f3lar australiano",JPY_displayName:"Iene japon\u00eas",USD_displayName:"D\u00f3lar norte-americano",GBP_displayName:"Libra esterlina brit\u00e2nica",EUR_displayName:"Euro",_localized:{}},"dijit/_editor/nls/commands":{bold:"Negrito",copy:"Copiar",cut:"Recortar","delete":"Excluir",indent:"Recuar",insertHorizontalRule:"R\u00e9gua Horizontal",insertOrderedList:"Lista Numerada",insertUnorderedList:"Lista com Marcadores",
italic:"It\u00e1lico",justifyCenter:"Alinhar pelo Centro",justifyFull:"Justificar",justifyLeft:"Alinhar pela Esquerda",justifyRight:"Alinhar pela Direita",outdent:"N\u00e3o-chanfrado",paste:"Colar",redo:"Refazer",removeFormat:"Remover Formato",selectAll:"Selecionar Todos",strikethrough:"Tachado",subscript:"Subscrito",superscript:"Sobrescrito",underline:"Sublinhado",undo:"Desfazer",unlink:"Remover Link",createLink:"Criar Link",toggleDir:"Comutar Dire\u00e7\u00e3o",insertImage:"Inserir Imagem",insertTable:"Inserir/Editar Tabela",
toggleTableBorder:"Alternar Moldura da Tabela",deleteTable:"Excluir Tabela",tableProp:"Propriedade da Tabela",htmlToggle:"Origem HTML",foreColor:"Cor do Primeiro Plano",hiliteColor:"Cor de segundo plano",plainFormatBlock:"Estilo de Par\u00e1grafo",formatBlock:"Estilo de Par\u00e1grafo",fontSize:"Tamanho da Fonte",fontName:"Nome da Fonte",tabIndent:"Recuo de Guia",fullScreen:"Comutar Tela Cheia",viewSource:"Visualizar Origem HTML",print:"Impress\u00e3o",newPage:"Nova P\u00e1gina",systemShortcut:'A a\u00e7\u00e3o "${0}" est\u00e1 dispon\u00edvel em seu navegador apenas usando um atalho do teclado. Use ${1}.',
ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/nls/common":{buttonOk:"OK",buttonCancel:"Cancelar",buttonSave:"Salvar",itemClose:"Fechar",_localized:{}}});
//# sourceMappingURL=dojo_pt-br.js.map