//>>built
define("dojo/nls/dojo_tr",{"dojo/cldr/nls/gregorian":{"days-standAlone-short":"Pa Pt Sa \u00c7a Pe Cu Ct".split(" "),"months-format-narrow":"O\u015eMNMHTAEEKA".split(""),"quarters-standAlone-narrow":["1.","2.","3.","4."],"field-weekday":"Haftan\u0131n G\u00fcn\u00fc","dateFormatItem-yQQQ":"y/QQQ","dateFormatItem-yMEd":"dd.MM.y E","dateFormatItem-GyMMMEd":"d MMM y G E","dateFormatItem-MMMEd":"d MMMM E",eraNarrow:["M\u00d6","MS"],"days-format-short":"Pa Pt Sa \u00c7a Pe Cu Ct".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"d MMMM y","months-format-wide":"Ocak \u015eubat Mart Nisan May\u0131s Haziran Temmuz A\u011fustos Eyl\u00fcl Ekim Kas\u0131m Aral\u0131k".split(" "),"dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"\u00d6S","dateFormat-full":"d MMMM y EEEE","dateFormatItem-Md":"dd/MM","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateFormatItem-yMd":"dd.MM.y","field-era":"Miladi D\u00f6nem","dateFormatItem-yM":"MM/y","months-standAlone-wide":"Ocak \u015eubat Mart Nisan May\u0131s Haziran Temmuz A\u011fustos Eyl\u00fcl Ekim Kas\u0131m Aral\u0131k".split(" "),
"timeFormat-short":"HH:mm","quarters-format-wide":["1. \u00e7eyrek","2. \u00e7eyrek","3. \u00e7eyrek","4. \u00e7eyrek"],"dateFormatItem-yQQQQ":"y/QQQQ","timeFormat-long":"HH:mm:ss z","field-year":"Y\u0131l","dateFormatItem-yMMM":"MMM y","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Saat","months-format-abbr":"Oca \u015eub Mar Nis May Haz Tem A\u011fu Eyl Eki Kas Ara".split(" "),"timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"Bug\u00fcn",
"field-day-relative+1":"Yar\u0131n","dateFormatItem-GyMMMd":"dd MMM y G","dateFormatItem-H":"HH","months-standAlone-abbr":"Oca \u015eub Mar Nis May Haz Tem A\u011fu Eyl Eki Kas Ara".split(" "),"quarters-format-abbr":["\u00c71","\u00c72","\u00c73","\u00c74"],"quarters-standAlone-wide":["1. \u00e7eyrek","2. \u00e7eyrek","3. \u00e7eyrek","4. \u00e7eyrek"],"dateFormatItem-Gy":"y G","dateFormatItem-M":"L","days-standAlone-wide":"Pazar Pazartesi Sal\u0131 \u00c7ar\u015famba Per\u015fembe Cuma Cumartesi".split(" "),
"timeFormat-medium":"HH:mm:ss","dateFormatItem-Hm":"HH:mm","quarters-standAlone-abbr":["\u00c71","\u00c72","\u00c73","\u00c74"],eraAbbr:["M\u00d6","MS"],"field-minute":"Dakika","field-dayperiod":"\u00d6\u00d6/\u00d6S","days-standAlone-abbr":"Paz Pzt Sal \u00c7ar Per Cum Cmt".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1.","2.","3.","4."],"field-day-relative+-1":"D\u00fcn","dateFormatItem-h":"h a","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"AM",
"dateFormatItem-MMMd":"d MMMM","dateFormatItem-MEd":"dd/MM E","dateTimeFormat-full":"{1} {0}","field-day":"G\u00fcn","days-format-wide":"Pazar Pazartesi Sal\u0131 \u00c7ar\u015famba Per\u015fembe Cuma Cumartesi".split(" "),"field-zone":"Saat Dilimi","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y","months-standAlone-narrow":"O\u015eMNMHTAEEKA".split(""),"dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Year":"{1} {0}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})",
"dayPeriods-format-abbr-pm":"PM","days-format-abbr":"Paz Pzt Sal \u00c7ar Per Cum Cmt".split(" "),eraNames:["Milattan \u00d6nce","Milattan Sonra"],"dateFormatItem-yMMMd":"dd MMM y","days-format-narrow":"PPS\u00c7PCC".split(""),"days-standAlone-narrow":"PPS\u00c7PCC".split(""),"dateFormatItem-MMM":"LLL","field-month":"Ay","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"\u00d6\u00d6","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})",
"dateFormat-short":"d.MM.y","field-second":"Saniye","dateFormatItem-yMMMEd":"d MMM y E","dateFormatItem-Ed":"d E","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"Hafta","dateFormat-medium":"d MMM y","dayPeriods-format-narrow-pm":"PM","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM y G","dateFormatItem-yMM":"MM.y","field-day-relative+2":"\u00d6b\u00fcr g\u00fcn","dateFormatItem-MMMMd":"dd MMMM","field-day-relative+-2":"Evvelsi g\u00fcn",
"dateFormatItem-yMMMM":"MMMM y","field-year-relative+-1":"Ge\u00e7en y\u0131l","field-month-relative+-1":"Ge\u00e7en ay","dateFormatItem-MMMMEd":"dd MMMM E","field-month-relative+0":"Bu ay","field-month-relative+1":"Gelecek ay","field-year-relative+0":"Bu y\u0131l","field-week-relative+-1":"Ge\u00e7en hafta","field-year-relative+1":"Gelecek y\u0131l","dateFormatItem-mmss":"mm:ss","field-week-relative+0":"Bu hafta","field-week-relative+1":"Gelecek hafta",_localized:{}},"dijit/nls/loading":{loadingState:"Y\u00fckleniyor...",
errorState:"\u00dczg\u00fcn\u00fcz, bir hata olu\u015ftu",_localized:{}},"dojox/grid/enhanced/nls/EnhancedGrid":{singleSort:"Tekli S\u0131ralama",nestedSort:"\u0130\u00e7 \u0130\u00e7e S\u0131ralama",ascending:"Artan S\u0131rada s\u0131ralamak i\u00e7in t\u0131klat\u0131n",descending:"Azalan S\u0131rada s\u0131ralamak i\u00e7in t\u0131klat\u0131n",sortingState:"${0} - ${1}",unsorted:"Bu s\u00fctunu s\u0131ralama",indirectSelectionRadio:"Sat\u0131r ${0}, tek se\u00e7imli, radyo d\u00fc\u011fmesi",
indirectSelectionCheckBox:"Sat\u0131r ${0}, \u00e7ok se\u00e7imli, radyo d\u00fc\u011fmesi",selectAll:"T\u00fcm\u00fcn\u00fc se\u00e7",_localized:{}},"dijit/form/nls/validate":{invalidMessage:"Girilen de\u011fer ge\u00e7ersiz.",missingMessage:"Bu de\u011fer gerekli.",rangeMessage:"Bu de\u011fer aral\u0131k d\u0131\u015f\u0131nda.",_localized:{}},"dijit/form/nls/ComboBox":{previousMessage:"\u00d6nceki se\u00e7enekler",nextMessage:"Di\u011fer se\u00e7enekler",_localized:{}},"dojo/cldr/nls/number":{scientificFormat:"#E0",
"currencySpacing-afterCurrency-currencyMatch":"[:^S:]",infinity:"\u221e",list:";",percentSign:"%",minusSign:"-","currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]","decimalFormat-short":"000\u00a0Tn","currencySpacing-afterCurrency-insertBetween":"\u00a0",nan:"NaN",plusSign:"+","currencySpacing-afterCurrency-surroundingMatch":"[:digit:]","currencySpacing-beforeCurrency-currencyMatch":"[:^S:]",currencyFormat:"#,##0.00\u00a0\u00a4;(#,##0.00\u00a0\u00a4)",perMille:"\u2030",group:".",percentFormat:"%#,##0",
"decimalFormat-long":"000 trilyon",decimalFormat:"#,##0.###",decimal:",","currencySpacing-beforeCurrency-insertBetween":"\u00a0",exponential:"E",_localized:{}},"dojo/cldr/nls/currency":{USD_symbol:"$",CAD_symbol:"CA$",GBP_symbol:"\u00a3",HKD_symbol:"HK$",JPY_symbol:"\u00a5",AUD_symbol:"AU$",CNY_symbol:"CN\u00a5",EUR_symbol:"\u20ac",HKD_displayName:"Hong Kong Dolar\u0131",CHF_displayName:"\u0130svi\u00e7re Frang\u0131",CAD_displayName:"Kanada Dolar\u0131",CNY_displayName:"\u00c7in Yuan\u0131",AUD_displayName:"Avustralya Dolar\u0131",
JPY_displayName:"Japon Yeni",USD_displayName:"ABD Dolar\u0131",GBP_displayName:"\u0130ngiliz Sterlini",EUR_displayName:"Euro",_localized:{}},"dijit/_editor/nls/commands":{bold:"Kal\u0131n",copy:"Kopyala",cut:"Kes","delete":"Sil",indent:"Girinti",insertHorizontalRule:"Yatay Kural",insertOrderedList:"Numaral\u0131 Liste",insertUnorderedList:"Madde \u0130\u015faretli Liste",italic:"\u0130talik",justifyCenter:"Ortaya Hizala",justifyFull:"Yasla",justifyLeft:"Sola Hizala",justifyRight:"Sa\u011fa Hizala",
outdent:"\u00c7\u0131k\u0131nt\u0131",paste:"Yap\u0131\u015ft\u0131r",redo:"Yinele",removeFormat:"Bi\u00e7imi Kald\u0131r",selectAll:"T\u00fcm\u00fcn\u00fc Se\u00e7",strikethrough:"\u00dcst\u00fc \u00c7izili",subscript:"Alt Simge",superscript:"\u00dcst Simge",underline:"Alt\u0131 \u00c7izili",undo:"Geri Al",unlink:"Ba\u011flant\u0131y\u0131 Kald\u0131r",createLink:"Ba\u011flant\u0131 Olu\u015ftur",toggleDir:"Y\u00f6n\u00fc De\u011fi\u015ftir",insertImage:"Resim Ekle",insertTable:"Tablo Ekle/D\u00fczenle",
toggleTableBorder:"Tablo Kenarl\u0131\u011f\u0131n\u0131 G\u00f6ster/Gizle",deleteTable:"Tabloyu Sil",tableProp:"Tablo \u00d6zelli\u011fi",htmlToggle:"HTML Kayna\u011f\u0131",foreColor:"\u00d6n Plan Rengi",hiliteColor:"Arka Plan Rengi",plainFormatBlock:"Paragraf Stili",formatBlock:"Paragraf Stili",fontSize:"Yaz\u0131 Tipi Boyutu",fontName:"Yaz\u0131 Tipi Ad\u0131",tabIndent:"Sekme Girintisi",fullScreen:"Tam Ekran\u0131 A\u00e7/Kapat",viewSource:"HTML Kayna\u011f\u0131n\u0131 G\u00f6r\u00fcnt\u00fcle",
print:"Yazd\u0131r",newPage:"Yeni Sayfa",systemShortcut:'"${0}" i\u015flemi yaln\u0131zca taray\u0131c\u0131n\u0131zda bir klavye k\u0131sayoluyla birlikte kullan\u0131labilir. \u015eunu kullan\u0131n: ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/nls/common":{buttonOk:"Tamam",buttonCancel:"\u0130ptal",buttonSave:"Kaydet",itemClose:"Kapat",_localized:{}}});
//# sourceMappingURL=dojo_tr.js.map