//>>built
define("dojo/nls/dojo_fi-fi",{"dojo/cldr/nls/gregorian":{"days-standAlone-short":"su ma ti ke to pe la".split(" "),"months-format-narrow":"THMHTKHESLMJ".split(""),"quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"viikonp\u00e4iv\u00e4","dateFormatItem-yQQQ":"QQQ y","dateFormatItem-yMEd":"E d.M.y","dateFormatItem-GyMMMEd":"E d. MMM y G","dateFormatItem-MMMEd":"ccc d. MMM",eraNarrow:["eK","jK"],"days-format-short":"su ma ti ke to pe la".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"d. MMMM y","months-format-wide":"tammikuuta helmikuuta maaliskuuta huhtikuuta toukokuuta kes\u00e4kuuta hein\u00e4kuuta elokuuta syyskuuta lokakuuta marraskuuta joulukuuta".split(" "),"dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"ip.","dateFormat-full":"cccc d. MMMM y","dateFormatItem-Md":"d.M.","dayPeriods-format-abbr-am":"ap.","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateFormatItem-yMd":"d.M.y","field-era":"aikakausi","dateFormatItem-yM":"L.y","months-standAlone-wide":"tammikuu helmikuu maaliskuu huhtikuu toukokuu kes\u00e4kuu hein\u00e4kuu elokuu syyskuu lokakuu marraskuu joulukuu".split(" "),
"timeFormat-short":"H.mm","quarters-format-wide":["1. nelj\u00e4nnes","2. nelj\u00e4nnes","3. nelj\u00e4nnes","4. nelj\u00e4nnes"],"dateFormatItem-yQQQQ":"QQQQ y","timeFormat-long":"H.mm.ss z","field-year":"vuosi","dateFormatItem-yMMM":"LLL y","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"tunti","months-format-abbr":"tammikuuta helmikuuta maaliskuuta huhtikuuta toukokuuta kes\u00e4kuuta hein\u00e4kuuta elokuuta syyskuuta lokakuuta marraskuuta joulukuuta".split(" "),"timeFormat-full":"H.mm.ss zzzz",
"dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"t\u00e4n\u00e4\u00e4n","field-day-relative+1":"huomenna","dateFormatItem-GyMMMd":"d. MMM y G","dateFormatItem-H":"H","months-standAlone-abbr":"tammi helmi maalis huhti touko kes\u00e4 hein\u00e4 elo syys loka marras joulu".split(" "),"quarters-format-abbr":["1. nelj.","2. nelj.","3. nelj.","4. nelj."],"quarters-standAlone-wide":["1. nelj\u00e4nnes","2. nelj\u00e4nnes","3. nelj\u00e4nnes","4. nelj\u00e4nnes"],"dateFormatItem-Gy":"y G",
"dateFormatItem-M":"L","days-standAlone-wide":"sunnuntai maanantai tiistai keskiviikko torstai perjantai lauantai".split(" "),"timeFormat-medium":"H.mm.ss","dateFormatItem-Hm":"H.mm","quarters-standAlone-abbr":["1. nelj.","2. nelj.","3. nelj.","4. nelj."],eraAbbr:["eKr.","jKr."],"field-minute":"minuutti","field-dayperiod":"vuorokaudenaika","days-standAlone-abbr":"su ma ti ke to pe la".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm.ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"eilen",
"dateFormatItem-h":"h a","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"ap.","dateFormatItem-MMMd":"d. MMM","dateFormatItem-MEd":"E d.M.","dateTimeFormat-full":"{1} {0}","field-day":"p\u00e4iv\u00e4","days-format-wide":"sunnuntaina maanantaina tiistaina keskiviikkona torstaina perjantaina lauantaina".split(" "),"field-zone":"aikavy\u00f6hyke","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y","months-standAlone-narrow":"THMHTKHESLMJ".split(""),"dateFormatItem-hm":"h.mm a",
"dateTimeFormats-appendItem-Year":"{1} {0}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"ip.","days-format-abbr":"su ma ti ke to pe la".split(" "),eraNames:["ennen Kristuksen syntym\u00e4\u00e4","j\u00e4lkeen Kristuksen syntym\u00e4n"],"dateFormatItem-yMMMd":"d. MMM y","days-format-narrow":"SMTKTPL".split(""),"days-standAlone-narrow":"SMTKTPL".split(""),"dateFormatItem-MMM":"LLL","field-month":"kuukausi","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"ap.",
"dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormat-short":"d.M.y","field-second":"sekunti","dateFormatItem-yMMMEd":"E d. MMM y","dateFormatItem-Ed":"E d.","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"viikko","dateFormat-medium":"d.M.y","dayPeriods-format-narrow-pm":"ip.","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"H.mm.ss","dateFormatItem-hms":"h.mm.ss a","dateFormatItem-GyMMM":"LLL y G","dateFormatItem-yMM":"M.y",
"dayPeriods-standAlone-wide-pm":"ip.","field-day-relative+2":"ylihuomenna","field-day-relative+-2":"toissap\u00e4iv\u00e4n\u00e4","dateFormatItem-yMMMM":"LLLL y","dateFormatItem-yMMMMccccd":"cccc d. MMMM y","field-year-relative+-1":"viime vuonna","field-month-relative+-1":"viime kuussa","dayPeriods-standAlone-wide-am":"ap.","field-month-relative+0":"t\u00e4ss\u00e4 kuussa","field-month-relative+1":"ensi kuussa","field-year-relative+0":"t\u00e4n\u00e4 vuonna","field-week-relative+-1":"viime viikolla",
"field-year-relative+1":"ensi vuonna","field-week-relative+0":"t\u00e4ll\u00e4 viikolla","field-week-relative+1":"ensi viikolla",_localized:{}},"dijit/nls/loading":{loadingState:"Lataus on meneill\u00e4\u00e4n...",errorState:"On ilmennyt virhe.",_localized:{}},"dojox/grid/enhanced/nls/EnhancedGrid":{singleSort:"Yksinkertainen lajittelu",nestedSort:"Sis\u00e4kk\u00e4inen lajittelu",ascending:"Lajittele nousevaan j\u00e4rjestykseen napsauttamalla",descending:"Lajittele laskevaan j\u00e4rjestykseen napsauttamalla",
sortingState:"${0} - ${1}",unsorted:"\u00c4l\u00e4 lajittele t\u00e4t\u00e4 saraketta",indirectSelectionRadio:"Rivi ${0}, yksi valinta, valintanappi",indirectSelectionCheckBox:"Rivi ${0}, useita valintoja, valintaruutu",selectAll:"Valitse kaikki",_localized:{}},"dijit/form/nls/validate":{invalidMessage:"Annettu arvo ei kelpaa.",missingMessage:"T\u00e4m\u00e4 arvo on pakollinen.",rangeMessage:"T\u00e4m\u00e4 arvo on sallitun alueen ulkopuolella.",_localized:{}},"dijit/form/nls/ComboBox":{previousMessage:"Edelliset valinnat",
nextMessage:"Lis\u00e4\u00e4 valintoja",_localized:{}},"dojo/cldr/nls/number":{scientificFormat:"#E0","currencySpacing-afterCurrency-currencyMatch":"[:^S:]",infinity:"\u221e",list:";",percentSign:"%",minusSign:"-","currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]","decimalFormat-short":"000\u00a0bilj'.'","currencySpacing-afterCurrency-insertBetween":"\u00a0",nan:"ep\u00e4luku",plusSign:"+","currencySpacing-afterCurrency-surroundingMatch":"[:digit:]","currencySpacing-beforeCurrency-currencyMatch":"[:^S:]",
currencyFormat:"#,##0.00\u00a0\u00a4",perMille:"\u2030",group:"\u00a0",percentFormat:"#,##0\u00a0%","decimalFormat-long":"000 biljoonaa",decimalFormat:"#,##0.###",decimal:",","currencySpacing-beforeCurrency-insertBetween":"\u00a0",exponential:"E",_localized:{}},"dojo/cldr/nls/currency":{USD_symbol:"$",CAD_symbol:"CAD",GBP_symbol:"\u00a3",HKD_symbol:"HKD",JPY_symbol:"\u00a5",AUD_symbol:"AUD",CNY_symbol:"CNY",EUR_symbol:"\u20ac",HKD_displayName:"Hongkongin dollari",CHF_displayName:"Sveitsin frangi",
CAD_displayName:"Kanadan dollari",CNY_displayName:"Kiinan yuan",AUD_displayName:"Australian dollari",JPY_displayName:"Japanin jeni",USD_displayName:"Yhdysvaltain dollari",GBP_displayName:"Englannin punta",EUR_displayName:"euro",_localized:{}},"dijit/_editor/nls/commands":{bold:"Lihavointi",copy:"Kopioi",cut:"Leikkaa","delete":"Poista",indent:"Sisenn\u00e4",insertHorizontalRule:"Vaakasuuntainen viiva",insertOrderedList:"Numeroitu luettelo",insertUnorderedList:"Numeroimaton luettelo",italic:"Kursivointi",
justifyCenter:"Tasaus keskelle",justifyFull:"Tasaus",justifyLeft:"Tasaus vasemmalle",justifyRight:"Tasaus oikealle",outdent:"Ulonna",paste:"Liit\u00e4",redo:"Tee uudelleen",removeFormat:"Poista muotoilu",selectAll:"Valitse kaikki",strikethrough:"Yliviivaus",subscript:"Alennettu",superscript:"Korotettu",underline:"Alleviivaus",undo:"Kumoa",unlink:"Poista linkki",createLink:"Luo linkki",toggleDir:"Vaihda suuntaa",insertImage:"Lis\u00e4\u00e4 kuva",insertTable:"Lis\u00e4\u00e4 taulukko/muokkaa taulukkoa",
toggleTableBorder:"Ota taulukon kehys k\u00e4ytt\u00f6\u00f6n/poista kehys k\u00e4yt\u00f6st\u00e4",deleteTable:"Poista taulukko",tableProp:"Taulukon ominaisuudet",htmlToggle:"HTML-l\u00e4hde",foreColor:"Edustav\u00e4ri",hiliteColor:"Taustav\u00e4ri",plainFormatBlock:"Kappaletyyli",formatBlock:"Kappaletyyli",fontSize:"Fonttikoko",fontName:"Fontin nimi",tabIndent:"Sarkainsisennys",fullScreen:"Vaihda koko n\u00e4ytt\u00f6",viewSource:"N\u00e4yt\u00e4 HTML-l\u00e4hde",print:"Tulosta",newPage:"Uusi sivu",
systemShortcut:'Toiminto "${0}" on k\u00e4ytett\u00e4viss\u00e4 selaimessa vain n\u00e4pp\u00e4imist\u00f6n pikatoiminnolla. K\u00e4yt\u00e4 seuraavaa: ${1}.',ctrlKey:"Ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/nls/common":{buttonOk:"OK",buttonCancel:"Peruuta",buttonSave:"Tallenna",itemClose:"Sulje",_localized:{}}});
//# sourceMappingURL=dojo_fi-fi.js.map