//>>built
define("dojo/nls/dojo_en-gb",{"dojo/cldr/nls/gregorian":{"days-standAlone-short":"Su Mo Tu We Th Fr Sa".split(" "),"months-format-narrow":"JFMAMJJASOND".split(""),"quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Day of the Week","dateFormatItem-yQQQ":"QQQ y","dateFormatItem-yMEd":"E, dd/MM/y","dateFormatItem-GyMMMEd":"E, d MMM y G","dateFormatItem-MMMEd":"E d MMM",eraNarrow:["B","A"],"days-format-short":"Su Mo Tu We Th Fr Sa".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"d MMMM y","months-format-wide":"January February March April May June July August September October November December".split(" "),"dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"pm","dateFormat-full":"EEEE, d MMMM y","dateFormatItem-Md":"dd/MM","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateFormatItem-yMd":"dd/MM/y","field-era":"Era","dateFormatItem-yM":"MM/y","months-standAlone-wide":"January February March April May June July August September October November December".split(" "),
"timeFormat-short":"HH:mm","quarters-format-wide":["1st quarter","2nd quarter","3rd quarter","4th quarter"],"dateFormatItem-yQQQQ":"QQQQ y","timeFormat-long":"HH:mm:ss z","field-year":"Year","dateFormatItem-yMMM":"MMM y","dateTimeFormats-appendItem-Era":"{0} {1}","field-hour":"Hour","months-format-abbr":"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),"timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"Today","field-day-relative+1":"Tomorrow",
"dateFormatItem-GyMMMd":"d MMM y G","dateFormatItem-H":"HH","months-standAlone-abbr":"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-wide":["1st quarter","2nd quarter","3rd quarter","4th quarter"],"dateFormatItem-Gy":"y G","dateFormatItem-M":"LL","days-standAlone-wide":"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),"timeFormat-medium":"HH:mm:ss","dateFormatItem-Hm":"HH:mm","quarters-standAlone-abbr":["Q1",
"Q2","Q3","Q4"],eraAbbr:["BC","AD"],"field-minute":"Minute","field-dayperiod":"am/pm","days-standAlone-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"Yesterday","dateFormatItem-h":"h a","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-MMMd":"d MMM","dateFormatItem-MEd":"E dd/MM","dateTimeFormat-full":"{1} {0}","field-day":"Day","days-format-wide":"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
"field-zone":"Time Zone","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y","months-standAlone-narrow":"JFMAMJJASOND".split(""),"dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Year":"{0} {1}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),eraNames:["Before Christ","Anno Domini"],"dateFormatItem-yMMMd":"d MMM y","days-format-narrow":"SMTWTFS".split(""),"days-standAlone-narrow":"SMTWTFS".split(""),
"dateFormatItem-MMM":"LLL","field-month":"Month","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"am","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormat-short":"dd/MM/y","field-second":"Second","dateFormatItem-yMMMEd":"E, d MMM y","dateFormatItem-Ed":"E d","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"Week","dateFormat-medium":"d MMM y","dayPeriods-format-narrow-pm":"p","dateTimeFormat-short":"{1} {0}",
"dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM y G","dateFormatItem-Ehm":"E h:mm a","dayPeriods-format-wide-noon":"noon","field-year-relative+-1":"Last year","field-month-relative+-1":"Last month","dateFormatItem-EHm":"E HH:mm","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-month-relative+0":"This month","field-month-relative+1":"Next month","field-year-relative+0":"This year","field-week-relative+-1":"Last week",
"field-year-relative+1":"Next year","field-week-relative+0":"This week","field-week-relative+1":"Next week","dateFormatItem-MMdd":"dd/MM","dateFormatItem-yMMMM":"MMMM y","dateFormatItem-MMMMd":"d MMMM",_localized:{}},"dijit/nls/loading":{loadingState:"Loading...",errorState:"Sorry, an error occurred",_localized:{}},"dojox/grid/enhanced/nls/EnhancedGrid":{singleSort:"Single Sort",nestedSort:"Nested Sort",ascending:"Click to sort Ascending",descending:"Click to sort Descending",sortingState:"${0} - ${1}",
unsorted:"Do not sort this column",indirectSelectionRadio:"Row ${0}, single selection, radio box",indirectSelectionCheckBox:"Row ${0}, multiple selection, check box",selectAll:"Select all",_localized:{}},"dijit/form/nls/validate":{invalidMessage:"The value entered is not valid.",missingMessage:"This value is required.",rangeMessage:"This value is out of range.",_localized:{}},"dijit/form/nls/ComboBox":{previousMessage:"Previous choices",nextMessage:"More choices",_localized:{}},"dojo/cldr/nls/number":{scientificFormat:"#E0",
"currencySpacing-afterCurrency-currencyMatch":"[:^S:]",infinity:"\u221e",list:";",percentSign:"%",minusSign:"-","currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]","decimalFormat-short":"000T","currencySpacing-afterCurrency-insertBetween":"\u00a0",nan:"NaN",plusSign:"+","currencySpacing-afterCurrency-surroundingMatch":"[:digit:]","currencySpacing-beforeCurrency-currencyMatch":"[:^S:]",currencyFormat:"\u00a4#,##0.00",perMille:"\u2030",group:",",percentFormat:"#,##0%","decimalFormat-long":"000 trillion",
decimalFormat:"#,##0.###",decimal:".","currencySpacing-beforeCurrency-insertBetween":"\u00a0",exponential:"E",_localized:{}},"dojo/cldr/nls/currency":{USD_symbol:"$",CAD_symbol:"CA$",GBP_symbol:"\u00a3",HKD_symbol:"HK$",JPY_symbol:"\u00a5",AUD_symbol:"AU$",CNY_symbol:"CN\u00a5",EUR_symbol:"\u20ac",HKD_displayName:"Hong Kong Dollar",CHF_displayName:"Swiss Franc",CAD_displayName:"Canadian Dollar",CNY_displayName:"Chinese Yuan",AUD_displayName:"Australian Dollar",JPY_displayName:"Japanese Yen",USD_displayName:"US Dollar",
GBP_displayName:"British Pound",EUR_displayName:"Euro",_localized:{}},"dijit/_editor/nls/commands":{bold:"Bold",copy:"Copy",cut:"Cut","delete":"Delete",indent:"Indent",insertHorizontalRule:"Horizontal Rule",insertOrderedList:"Numbered List",insertUnorderedList:"Bullet List",italic:"Italic",justifyCenter:"Align Center",justifyFull:"Justify",justifyLeft:"Align Left",justifyRight:"Align Right",outdent:"Outdent",paste:"Paste",redo:"Redo",removeFormat:"Remove Format",selectAll:"Select All",strikethrough:"Strikethrough",
subscript:"Subscript",superscript:"Superscript",underline:"Underline",undo:"Undo",unlink:"Remove Link",createLink:"Create Link",toggleDir:"Toggle Direction",insertImage:"Insert Image",insertTable:"Insert/Edit Table",toggleTableBorder:"Toggle Table Border",deleteTable:"Delete Table",tableProp:"Table Property",htmlToggle:"HTML Source",foreColor:"Foreground Color",hiliteColor:"Background Color",plainFormatBlock:"Paragraph Style",formatBlock:"Paragraph Style",fontSize:"Font Size",fontName:"Font Name",
tabIndent:"Tab Indent",fullScreen:"Toggle Full Screen",viewSource:"View HTML Source",print:"Print",newPage:"New Page",systemShortcut:'The "${0}" action is only available in your browser using a keyboard shortcut. Use ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/nls/common":{buttonOk:"OK",buttonCancel:"Cancel",buttonSave:"Save",itemClose:"Close",_localized:{}}});
//# sourceMappingURL=dojo_en-gb.js.map